FROM registry.access.redhat.com/ubi8/nginx-118:latest

USER root

RUN dnf install -y yum-utils

ENTRYPOINT ["reposync", "-a", "x86_64", "--repoid", "rhel-8-for-x86_64-baseos-rpms", "-p", "/repo", "--download-metadata"]
