kind: Template
apiVersion: v1
metadata:
  name: rhods-entitled-mirror
  annotations:
    openshift.io/display-name: Entitled mirror repository with packages for building GPU drivers
    description: ""
    tags: nginx,entitlement,mirror
    iconClass: icon-nginx
    openshift.io/long-description: ""
    openshift.io/provider-display-name: PSAP
    openshift.io/documentation-url: rhods-entitled-mirror
    openshift.io/support-url: ""
message: ""
labels:
  template: rhods-entitled-mirror
objects:
  - kind: Namespace
    apiVersion: v1
    metadata:
        name: ${NAMESPACE}
  - kind: Service
    apiVersion: v1
    metadata:
      namespace: ${NAMESPACE}
      name: ${NAME}
    spec:
      ports:
        - name: web
          port: 8080
          targetPort: 8080
      selector:
        app: ${NAME}
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
      annotations:
        template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    spec:
      host: ${APPLICATION_DOMAIN}
      to:
        kind: Service
        name: ${NAME}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
  - apiVersion: security.openshift.io/v1
    kind: SecurityContextConstraints
    metadata:
      name: ${NAME}
    priority: null
    readOnlyRootFilesystem: false
    requiredDropCapabilities: null
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: RunAsAny
    seccompProfiles:
      - '*'
    supplementalGroups:
      type: RunAsAny
    users:
      - system:serviceaccount:${NAMESPACE}:${NAME}
    volumes:
      - '*'
    allowHostDirVolumePlugin: true
    allowHostIPC: false
    allowHostNetwork: false
    allowHostPID: true
    allowHostPorts: false
    allowPrivilegeEscalation: true
    allowPrivilegedContainer: true
    allowedCapabilities:
      - '*'
    allowedUnsafeSysctls:
      - '*'
    defaultAddCapabilities: null
    fsGroup:
      type: RunAsAny
    groups:
      - system:cluster-admins
      - system:nodes
      - system:masters
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: ${NAME}
      template:
        metadata:
          name: ${NAME}
          labels:
            app: ${NAME}
        spec:
          serviceAccount: ${NAME}
          serviceAccountName: ${NAME}
          nodeSelector:
            entitled: "true"
          volumes:
            - name: repo
              persistentVolumeClaim:
                claimName: ${NAME}
          initContainers:
            - name: reposync
              image: quay.io/otuchfel/rhods-mirror-sync:latest
              securityContext:
                privileged: true
              volumeMounts:
                - name: repo
                  mountPath: /repo
          containers:
            - name: nginx
              image: quay.io/otuchfel/rhods-mirror-serve:latest
              volumeMounts:
                - name: repo
                  mountPath: /repo
              ports:
                - containerPort: 8080
              readinessProbe:
                timeoutSeconds: 3
                initialDelaySeconds: 3
                httpGet:
                  path: /rhel-8-for-x86_64-baseos-rpms/repodata/repomd.xml
                  port: 8080
              livenessProbe:
                timeoutSeconds: 3
                initialDelaySeconds: 30
                httpGet:
                  path: /rhel-8-for-x86_64-baseos-rpms/repodata/repomd.xml
                  port: 8080
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the frontend objects defined in this template.
    required: true
    value: ""
  - name: NAMESPACE
    displayName: Namespace
    description: The OpenShift Namespace where the ImageStream resides.
    required: true
    value: ""
  - name: APPLICATION_DOMAIN
    displayName: Application Hostname
    description: The exposed hostname that will route to the nginx service, if left blank a value will be defaulted.
    value: ""
